
set(MODEL_FILES
        ${CMAKE_CURRENT_LIST_DIR}/Column.h
        ${CMAKE_CURRENT_LIST_DIR}/Column.cpp
        ${CMAKE_CURRENT_LIST_DIR}/LeadsTableModel.h
        ${CMAKE_CURRENT_LIST_DIR}/LeadsTableModel.cpp
        ${CMAKE_CURRENT_LIST_DIR}/ColumnMissingException.h
        ${CMAKE_CURRENT_LIST_DIR}/ColumnMissingException.cpp
        ${CMAKE_CURRENT_LIST_DIR}/ColumnTree.h
        ${CMAKE_CURRENT_LIST_DIR}/ColumnTree.cpp
        ${CMAKE_CURRENT_LIST_DIR}/ColumnTreeItem.h
        ${CMAKE_CURRENT_LIST_DIR}/ColumnTreeItem.cpp
        ${CMAKE_CURRENT_LIST_DIR}/NewColumnsList.h
        ${CMAKE_CURRENT_LIST_DIR}/NewColumnsList.cpp
        ${CMAKE_CURRENT_LIST_DIR}/PageTreeItem.h
        ${CMAKE_CURRENT_LIST_DIR}/PageTreeItem.cpp
        ${CMAKE_CURRENT_LIST_DIR}/PageTree.h
        ${CMAKE_CURRENT_LIST_DIR}/PageTree.cpp
        ${CMAKE_CURRENT_LIST_DIR}/EmailTree.h
        ${CMAKE_CURRENT_LIST_DIR}/EmailTree.cpp
        ${CMAKE_CURRENT_LIST_DIR}/EmailTreeItem.h
        ${CMAKE_CURRENT_LIST_DIR}/EmailTreeItem.cpp
    )
